;/*FB_PKG_DELIM*/

__d("LSDeleteAllDeliverySettingWarnings",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[];return b.resolve(c)}a.__sproc_name__="LSOmnistoreSettingsDeleteAllDeliverySettingWarningsStoredProcedure";e.exports=a}),null);
__d("LSDeleteBannersByIds",["LSArrayGetObjectAt"],(function(a,b,c,d,e,f){function a(){var a=arguments,c=a[a.length-1],d=[],e=[];return c.sequence([function(e){return c.sequence([function(e){return c.sequence([function(e){return d[1]=c.createArray(),d[2]=c.i64.of_int32(a[1].length),c.i64.gt(d[2],c.i64.cast([0,0]))?c.loopAsync(d[2],function(e){return d[4]=e,c.sequence([function(e){return c.nativeTypeOperation("Array",b("LSArrayGetObjectAt"),a[1],d[4]).then(function(a){return a=a,d[5]=a[0],d[6]=a[1],a})},function(a){return d[7]=(d[1].push(c.i64.to_string(d[5])),d[1])}])}):c.resolve()},function(a){return d[3]=d[1].join(","),d[0]=d[3]}])},function(b){return c.forEach(c.filter(c.db.table(118).fetch([[[a[0]]]]),function(b){return c.i64.eq(b.threadKey,a[0])&&a[1].some(function(a){return c.i64.eq(b.bannerId,a)})}),function(a){return a["delete"]()})}])},function(a){return c.resolve(e)}])}a.__sproc_name__="LSInThreadBannerDeleteBannersByIdsStoredProcedure";e.exports=a}),null);
__d("LSDeleteThenInsertDeliverySetting",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[];return b.sequence([function(c){return b.db.table(148).put({audience:a[0],deliverySetting:a[1],deliveryOptions:a[2],usernameToDeliverySetting:a[3]})},function(a){return b.resolve(c)}])}a.__sproc_name__="LSOmnistoreSettingsDeleteThenInsertDeliverySettingStoredProcedure";e.exports=a}),null);
__d("LSInsertDeliverySettingWarning",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[];return b.resolve(c)}a.__sproc_name__="LSOmnistoreSettingsInsertDeliverySettingWarningStoredProcedure";e.exports=a}),null);
__d("LSStoryContactSyncFromBucket",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[],d=[];return b.sequence([function(a){return b.sequence([function(a){return b.forEach(b.filter(b.db.table(7).fetch(),function(a){return!0}),function(a){var b=a.update;a.item;return b({profileRingColor:void 0,profileRingState:void 0})})},function(a){return b.forEach(b.filter(b.db.table(53).fetch(),function(a){return b.i64.eq(a.bucketType,b.i64.cast([0,1]))}),function(a){var d=a.item;return c[1]=d.readState,b.i64.eq(c[1],b.i64.cast([0,1]))?c[0]=b.i64.cast([0,39423]):(b.i64.eq(c[1],b.i64.cast([0,2]))?c[2]=b.i64.cast([0,14342874]):c[2]=void 0,c[0]=c[2]),b.forEach(b.filter(b.db.table(7).fetch([[[d.ownerId]]]),function(a){return b.i64.eq(a.id,d.ownerId)&&b.i64.eq(b.i64.cast([0,1]),b.i64.cast([0,1]))}),function(a){var b=a.update;a.item;return b({profileRingState:c[1],profileRingColor:c[0]})})})}])},function(a){return b.resolve(d)}])}a.__sproc_name__="LSStoriesStoryContactSyncFromBucketStoredProcedure";e.exports=a}),null);
__d("LSTruncateFeatureLimits",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[];return b.sequence([function(a){return b.forEach(b.db.table(150).fetch(),function(a){return a["delete"]()})},function(a){return b.resolve(c)}])}a.__sproc_name__="LSOmnistoreSettingsTruncateFeatureLimitsStoredProcedure";e.exports=a}),null);
__d("LSTruncateReachabilitySettings",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[];return b.sequence([function(a){return b.forEach(b.db.table(148).fetch(),function(a){return a["delete"]()})},function(a){return b.resolve(c)}])}a.__sproc_name__="LSOmnistoreSettingsTruncateReachabilitySettingsStoredProcedure";e.exports=a}),null);
__d("LSUpdateOrInsertOhaiGatewayKeyConfigs",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1],c=[];return b.sequence([function(c){return b.db.table(313).put({keyId:a[0],publicKey:a[1],kemId:a[2],kdfId:a[3],aeadId:a[4],expirationDate:a[5],lastUpdatedTime:a[6]})},function(a){return b.resolve(c)}])}a.__sproc_name__="LSOhaiUpdateOrInsertOhaiGatewayKeyConfigsStoredProcedure";e.exports=a}),null);